In [1]:
import pandas as pd
import numpy as np
from scipy import stats as st

In [2]:
control = pd.read_csv("control_group.csv")
control.head()

  person_id  recovery_time_hrs
0      C001                4.4
1      C002                4.1
2      C003                3.2
3      C004                4.3
4      C005                4.9

In [3]:
test = pd.read_csv("test_group.csv")
test.head()

  person_id  recovery_time_hrs
0      T001                3.7
1      T002                4.1
2      T003                3.7
3      T004                3.9
4      T005                3.7

In [7]:
control_mean = control.recovery_time_hrs.mean().round(2)
control_std = control.recovery_time_hrs.std().round(2)
control_size = control.shape[0]
control_mean, control_std, control_size

(np.float64(4.0), np.float64(0.48), 130)

In [8]:
test_mean = test.recovery_time_hrs.mean().round(2)
test_std = test.recovery_time_hrs.std().round(2)
test_size = test.shape[0] 
test_mean, test_std, test_size

(np.float64(3.91), np.float64(0.32), 100)

In [15]:
a = (control_std**2/control_size)
b = (test_std**2/test_size)

Z_score = (control_mean-test_mean)/np.sqrt(a+b)
Z_score

np.float64(1.701962671923127)

In [17]:
critical_z_value = st.norm.ppf(1-0.05)
critical_z_value

np.float64(1.6448536269514722)

In [18]:
Z_score > critical_z_value

np.True_

In [19]:
p_value = 1- st.norm.cdf(Z_score)
p_value

np.float64(0.0443811829929599)

In [20]:
p_value < 0.05

np.True_